services:
  db:
    image: postgres:14
    container_name: pyledger-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pyledger
      POSTGRES_USER: pyledger_user
      POSTGRES_PASSWORD: pyledger_pass
    volumes:
      - pyledger_postgres_data:/var/lib/postgresql/data

volumes:
  pyledger_postgres_data:
